### ISSUE TITLE
Ajout de Rizomo

### ISSUE THREAD

**Issue by jdauphant** [betagouv/conferences#194]
## Demande
Le déploiement de la pastille démarre à partir d'aujourd'hui, pouvez-vous ajouter la ligne 

<script  type="text/javascript" src="https://rizomo.numerique.gouv.fr/scripts/widget"></script>

dans le header des pages du site [audioconf.numerique.gouv.fr](http://audioconf.numerique.gouv.fr/)

et dans le même temps ajouter la ligne
<script  type="text/javascript" src="https://rizomo-demo.numerique.gouv.fr/scripts/widget"></script>

sur le site de pre-prod/test/integration de audiconf

## Implémentation technique 

Variable d'environnement : RIZOMO_SCRIPT, si la variable est présente intégrer le code JS : `<script  type="text/javascript" src="$RIZOMO_SCRIPT"></script>` en bas du code de toutes les pages 

## Note
Est-ce que le script devrait être présent sur les pages où le numéro de conférence est visible ? ou la page de contrôle de la conférence ?

**Comment by celiacheff** [comment]
Qu'en est-il pour la dernière question ? On ajoute globalement ou pas ?

**Comment by jdauphant** [comment]
Il ne faudrait pas que ça soit présent sur la page de réservation ni la page de contrôle de la conférence.
Une première version peut juste être sur la home et on étendra après.

**Comment by celiacheff** [comment]
Ok
